development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mard_desarrollo
  pool: 5
  username: root
  password: inspiron
  shost: localhost
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mard_test
  pool: 5
  username: root
  password: inspiron
  shost: localhost
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mard_p
  pool: 5
  username: root
  password: inspiron
  shost: localhost